### ISSUE TITLE
Player can't deal with the screen before impoppable and chimps mode

### ISSUE THREAD

**Issue by v00d0079** [piweiblen/BloonsPlayer#1]
Hello, I wanted to let you know that I adore your bloons bot. I wanted to see if there was anyway you could implement a method that clears the menu screens that popup after the map has loaded for given modes. My current solution to this is to try and place a phantom dart monkey after the screen arrives which has caused some issues.

**Comment by piweiblen** [comment]
Thank you, glad you like it. This issue should be fixed properly. If you want to send me scripts for impoppable/chimps I'd be interested to see what you've come up with.

**Comment by v00d0079** [comment]
Sure just let me know the best way to send you the scripts is and I'll send what I came up with

**Comment by piweiblen** [comment]
Putting them here should be okay. If they are prohibitively long, you could upload a file somewhere and drop the link here.

**Comment by piweiblen** [comment]
I've made a discord server now. Feel free to join the discourse https://discord.gg/uJfudc3RfV
